// Package goplayv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package goplayv1

// InfoResponse defines model for InfoResponse.
type InfoResponse struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}
